spring:

  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none # delegated flyway
    show-sql: false # delegated to hibernate properties
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    initialization-mode: embedded

  flyway:
    enabled: true
    locations: classpath:/db/migration
    schemas: mw2
    table: purchase_order_flyway_history
  http:
    converters:
      preferred-json-mapper: jackson

logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG


management:
  endpoint:
    metrics:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /act

