spring:

  jpa:
    database: mysql
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: none # delegated flyway
    show-sql: true # delegated to hibernate, temporary is ON!
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/mworld?useSSL=false
    username: smicro
    password: smicro
    initialization-mode: embedded

  flyway:
    enabled: true
    locations: classpath:/db/migration


logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
