spring:

  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none # delegated flyway
    show-sql: false # delegated to hibernate properties
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    initialization-mode: embedded

  flyway:
    enabled: true
    locations: classpath:/db/migration
    table: customer_flyway_history
    schemas: mw1

  http:
    converters:
      preferred-json-mapper: jackson

  cloud:
    stream:
      bindings:
        customerOutChannel:  # name of the channel
          destination: customerChangedTopic  # name of the message queue
          contentType: application/json
          durableSubscription: true


logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/auth/userinfo

