INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (1,1,'Apple MacBook Pro','2018-08-01');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (5,2,'Apple iPhone','2018-08-05');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (6,2,'Sony TV','2018-08-01');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (7,3,'Amazon Kindle','2018-08-03');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (8,3,'Wooden table','2018-08-03');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (9,1,'Java EE in Action Book','2018-08-02');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (10,5,'Spring Boot in Action Book','2018-08-01');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (11,3,'Hersey\'s chocolate','2018-08-05');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (12,5,'WD HDD','2018-08-05');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (13,4,'Chessboard','2018-07-24');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (14,4,'Printer ink','2018-07-24');
INSERT INTO purchase_order (order_id,customer_id,item,order_date) VALUES (15,4,'Printer ink','2018-07-24');